name: genaiws
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pandas
  - jupyter
  - streamlit>=1.31
  - langchain
  - langchain-community
  - huggingface_hub 
  - pytorch
  - transformers
  - accelerate
  - chromadb
  - pytest
  - pip
  - pip: 
    - arxiv
    - deepeval
    - duckduckgo-search
    - langchain-openai
    - langchainhub
    - mediawikiapi
    - numexpr
    - openai
    - pypdf2
    - semanticscholar
    - tiktoken
    - wikibase-rest-api-client
    - wikipedia
    - xmltodict
