name: genai
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - jupyter
  - streamlit>=1.31
  - langchain
  - langchain-community
  - huggingface_hub 
  - pytorch
  - transformers
  - accelerate
  - chromadb
  pip:
    - requests~=2.31.0
    - python-dotenv~=1.0.1
    - PyPDF2~=3.0.1
    - langchain~=0.1.17
    - langchain-community~=0.0.36
    - langchain-core~=0.1.48
    - langchain-openai~=0.1.4
    - wikipedia~=1.4.0
    - chroma-hnswlib==0.7.3
    - chromadb==0.5.0
    - langchainhub~=0.1.15
    - sentence-transformers~=2.7.0
    - transformers~=4.40.1

